version: '3.9'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: pfe
    volumes:
      - mysql-data:/var/lib/mysql
      - ./MedBack-master/IMPORT/:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mysql-container
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "8081:80"
    depends_on:
      - mysql

  backend:
    build: ./MedBack-master
    container_name: rh-springboot-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/pfe
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
    ports:
      - "8090:8080"
    depends_on:
      - mysql

  frontend:
    build: ./Front-master
    container_name: rh-angular-container
    ports:
      - "4200:4200"
    command: npm start
    volumes:
      - ./Front-master:/app  # Ensure correct project directory is mapped
    depends_on:
      - backend

volumes:
  mysql-data:
 